openapi: 3.0.0
info:
  title: Crowd Service API
  description: This is the Crowd Service API
  version: 0.0.1
paths:
  /crowd/booking:
    post:
      summary: Returns a list of matching providers
      description: Find all the providers that matching the booking request
      requestBody:
        description: Booking Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':    
          description: A JSON array of matching providers
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Provider'
        '500':    
          description: Server response error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: "RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000"
  /loginPage:
    post:
      summary: Login backend site
      description: According to different roles (Manager, Dispatcher, Packer, Driver), login backend site
      requestBody:
        description: User Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':    
          description: Login successfully
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/LoginResponse'
        '400':    
          description: Server response error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: "Login Error"
  /order/{orderNumber}:
    get:
      summary: Get Orders by Order Number
      parameters:
        - in: path
          name: orderNumber
          schema:
            type: string
          required: true
          description: Get Orders by Order Number
      responses:
        '200':    
          description: An JSON of the order
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Order'
        '400':    
          description: Bad Request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
              example:
                message: "Data not found"
components:
  schemas:
    BookingRequest:
      type: object
      properties:
        from:
          $ref: '#/components/schemas/Address'
        to:
          $ref: '#/components/schemas/Address'
        jobId:
          type: number
      example:
        from:
          street: "287 Churchill Avenue"
          postcode: 7005
          country: "AU"
        to:
          street: "8 Apsley St"
          postcode: 7004
          country: "AU"
        jobId: 1
    Address:
      type: object
      properties:
        street:
          type: string
        postcode:
          type: number
        country:
          type: string
    Provider:
      type: object
      properties:
        id:
          type: string
        providerCode:
          type: string
        providerName:
          type: string
        providerDescription:
          type: string
        companyName:
          type: string
        address:
          $ref: '#/components/schemas/ProviderAddress'
        business:
          $ref: '#/components/schemas/Business'
        jobIds:
          type: string
        rating:
          type: string
        location:
          $ref: '#/components/schemas/Location'
      example:
        providerCode: "DEF"
        providerName: "Provider North Hobart"
        providerDescription: "Shipping and Delivery Provider"
        companyName: "Company Name"
        address: 
            address: "412 Elizabeth St"
            state: "Tasmania"
            city: "Hobart"
            suburb: "North Hobart"
            postCode: 7005
            country: "AU"
        business: 
            abnNumber: "51 824 753 556"
            lineNumber: "0491 570 156"
            documents: [ 1 ]
        jobIds: [ 1 ]
        rating: "5"
        location: 
          lat: -42.8750462
          lng: 147.3174775
    ProviderAddress:
      type: object
      properties:
        address:
          type: string
        state:
          type: string
        city:
          type: string
        suburb:
          type: string
        postCode:
          type: string
        country:
          type: string
      example:
        address: "412 Elizabeth St"
        state: "Tasmania"
        city: "Hobart"
        suburb: "North Hobart"
        postCode: 7005
        country: "AU"
    Location:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
      example:
        lat: -42.8750462
        lng: 147.3174775
    Business:
      type: object
      properties:
        abnNumber:
          type: string
        lineNumber:
          type: string
        documents:
          type: array
          items:
            type: integer
            format: int64
      example:
        abnNumber: "51 824 753 556t"
        lineNumber: "0491 570 156"
        documents: [ 1 ]
    ResponseBody:
      type: object
      properties:
        message:
          type: string
    UserRequest:
      type: object
      properties:
        role:
          type: string
        username:
          type: string
        password:
          type: string
      example:
        role: "packer"
        username: "packer1"
        password: "123456"
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
        role:
          type: string
      example:
        message: "login successfully"
        user:
            username: "packer1"
            password: "$2b$10$eNDcvieJhgvVuWp.aotLAerVPt0pgPflGc9AK17wMOEJkKjC3Ra5S"
            name: "Packer 1"
            address: ""
            email: ""
            gender: ""
            phone: ""
            photo: ""
        token: ""
        role: "packer"
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        name:
          type: string
        address:
          type: string
        email:
          type: string
        gender:
          type: string
        phone:
          type: string
        photo:
          type: string
      example:
        username: "packer1"
        password: "$2b$10$eNDcvieJhgvVuWp.aotLAerVPt0pgPflGc9AK17wMOEJkKjC3Ra5S"
        name: "Packer 1"
        address: ""
        email: ""
        gender: ""
        phone: ""
        photo: ""
    Order:
      type: object
      properties:
        createDate:
          type: string
          format: date-time
        shipmentStatus:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              date:
                type: string
                format: date-time
        paymentStatus:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              date:
                type: string
                format: date-time
        currencyCode:
          type: string
        remark:
          type: string
        totalAmount:
          type: number
        customer:
          type: string
        car:
          type: string
        driver:
          type: string
        parcelQty:
          type: number
        prefferedDeliveryDate:
          type: string
          format: date-time
        need_fridge:
          type: boolean
        sender:
          type: string
        consignmentID:
          type: string
        orderNumber:
          type: string
      example:
        createDate: "2023-04-01T10:30:00.000Z"
        shipmentStatus: 
          status: "prepared"
          date: "2023-04-01T00:00:00.000Z"
        paymentStatus:
          status: "unpaid"
          date: "2023-04-01T00:00:00.000Z"
        csurrencyCode: "AUD"
        remark": ""
        totalAmount: 420
        customer": "6435531588941c5e51959bc1"
        car: "643554d888941c5e51959bc3"
        driver: "643557b065b8ad5725de954b"
        parcelQty: 3
        prefferedDeliveryDate: "2023-04-01T00:00:00.000Z"
        need_fridge: true
        sender: "643fc42ac4fbf335914624c7"
        consignmentID: ""
        orderNumber: "SOF003101"